title: Life of Saahith
author: Saahith Matam
theme: minima
email: SYM170000@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
 Hi! I am Saahith Matam, a Junior studying computer science at UTD. I can not wait for another great year to learning more!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
